version: 2

sources:
  - name: snowflake_sample_data # this is the source_name
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL

    tables:
      - name: store_sales # this is the table_name
        description: "Details about the store sales"